### ISSUE TITLE
Support the case where a TA binary is supplied by a Client App

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#3] opened 2018-08-02 17:03 UTC
Currently the TEEP architecture draft supports TAM to distribute a TA binary and device specific information. It calls for further work to support the case where a TA binary is supplied by a Client Application. This is the case how GSX distributes a TA today.

The case support is considered in scope in IETF 101 TEEP WG discussion. See more TEEP mailing discussion with David Wheeler.

One of the original motivation to require a TAM is that both TA binary and any device specific configuration for the TA will be encrypted when it is sent to a device, ensuring better protection of TA binary. It has some challenge to still meet this security property if a TA binary is included in a Client Application in an Application Store. We could lower the security requirement that TA binary is just signed and make encryption optional. We need to work out the related verification protocol specification in the TEE side.

**Comment by mingpeiwk** [comment] 2018-08-02 18:59
On TA binary and data encryption, there was some proposal and prior arts to include "encrypted" TA binary inside a Client Application by the application developer. The decryption key of the TA binary is managed by a TAM that the application developer uses. During the TA installation time, such a key is shared with a device TEE upon certain authentication and authorization check.

**Comment by hannestschofenig** [comment] 2018-12-10 17:18
Raised during IETF#103: 

Issue #3 (Trusted App Distribution) needs to be complemented by a further issue
statement about how to coordinate version management between TEE and application
(i.e. so that it's clear which element is responsible for detecting/managing any
mismatches or invalid configurations).

**Comment by hannestschofenig** [comment] 2019-03-04 19:11
Can we support this use case by making encryption optional?

**Comment by mingpeiwk** [comment] 2019-03-04 19:12
I think this should the good way to give the option and constraint. For personalization data, TA can pull from TAM upon the binary installation.

**Comment by hannestschofenig** [comment] 2019-03-04 19:18
> statement about how to coordinate version management between TEE and application

if the TA is provided together with the client app then one can assume that the two work together (particularly since there is no TAM in the loop here to provide additional checking in real time).

**Comment by mingpeiwk** [comment] 2019-03-04 19:19
With a client bundled TA binary, we also need to expand "TA trust check" logic by a TEE in the device. Currently a device TEE has trust anchors that is used to trust a TAM for TA installation and management. This should expand to signer of TAs for trust check.

**Comment by hannestschofenig** [comment] 2019-03-04 19:24
If the TA is distributed separately from the Client App then version incompatibilities can arise. We would either need a software naming & versioning scheme or some form of query scheme to detect these version challenges.

**Comment by dmwheel1** [comment] 2019-03-08 20:34
Please see pull request to provide intro to this. Needs more work, but agreement on the way I have presented the problem is needed.

**Comment by dthaler** [comment] 2019-06-20 21:47
Verified addressed in the document.  Any additional issues can be filed as new issues.

**Closed as completed by dthaler** 2019-06-20 21:47 UTC
