### ISSUE TITLE
Agent and TEEP Broker used concurrently

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#57] opened 2019-05-09 09:06 UTC
Related to issue #16 : the architecture document uses both the terms "Agent" and "TEEP Broker". According to issue #16, the decision is only to use the term "broker".

Suggestion: replace the terms "agent" and "TEEP broker" with  "broker".

**Comment by dthaler** [comment] 2019-06-20 22:03
Agent and broker are different things.  The Agent runs inside the TEE and the Broker runs outside the TEE.  Propose closing this as by design.

**Comment by dthaler** [comment] 2019-08-20 20:21
Closing per discussion at IETF 105 where this was on the list of issues to be closed.

**Closed as completed by dthaler** 2019-08-20 20:21 UTC
